### PR TITLE
Allow PHPStan 2

### PR DESCRIPTION
**Pull request by samsonasik**
Ref https://github.com/rectorphp/rector/issues/8815?notification_referrer_id=NT_kwDOAAcDgLIxMjI1MTAyMjIwODo0NTk2NDg#issuecomment-2467650397

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Please read the upgrading guide before you attempt to upgrade.

**Comment by ondrejmirtes** [comment]
The upgrading guide says:

Please switch to PHPStan 2.0 in a new major version of your extension. It's not feasible to try to support both PHPStan 1.x and PHPStan 2.x with the same extension code.

You can definitely get closer to supporting PHPStan 2.0 without increasing major version by solving reported deprecations and other issues by analysing your extension code with PHPStan & phpstan-deprecation-rules & Bleeding Edge, but the final leap and solving backward incompatibilities should be done by requiring "phpstan/phpstan": "^2.0" in your composer.json, and releasing a new major version.

**Comment by ondrejmirtes** [comment]
Here's the link: https://github.com/phpstan/phpstan-src/blob/2.0.x/UPGRADING.md

**Comment by samsonasik** [comment]
Thank you, I will look on dependency tree, as it require-dev-ing rector, which rector still require phpstan 1.

I will check if it possibly check on `symplify/phpstan-rules` first, with temporary remove rector dependency to allow its phpstan extensions first...

**Comment by carlos-granados** [comment]
I checked this repo and after upgrading to PHPStan 2.0 no further changes are needed, al PHPStan and PHPUnit tests pass

**Pull request merged**
